[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_frontier = "BFD3zCe35aSdWeHHfpeVtMCUmbX584w8dJZAvcLR4WDp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
