[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_anchor = "8qECgGYj14f3aY1vLSN58SwCxkB9YYZBgh7xizJHiwY4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
